# Generated by Django 3.2 on 2022-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
