# Generated by Django 3.2 on 2022-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
