# Generated by Django 3.2 on 2022-11-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221110_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='main_camera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.store'),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.store'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cameras', to='users.store'),
        ),
    ]
