# Generated by Django 4.0.6 on 2022-09-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_video_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
