# Generated by Django 4.0.6 on 2022-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtsp_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='rtsp url')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='record_video/%Y%m%d/', verbose_name='이미지')),
                ('datetime', models.DateTimeField(verbose_name='날짜')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='같은클립')),
            ],
        ),
    ]
