# Generated by Django 3.2 on 2022-11-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtsp_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='rtsp url')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FilePathField(blank=True, null=True, path='/Users/ihyeonseung/Documents/ai_cctv/media/record_video/20221108', verbose_name='영상')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='상태')),
                ('datetime', models.DateTimeField(verbose_name='날짜')),
            ],
        ),
    ]
