# Generated by Django 4.1.1 on 2022-10-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_video_profile_delete_camera_delete_video'),
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='record_video/%Y%m%d/', verbose_name='이미지')),
                ('count', models.IntegerField(default=0, verbose_name='횟수')),
                ('datetime', models.DateTimeField(verbose_name='날짜')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='같은클립')),
                ('profile', models.ForeignKey(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
