# Generated by Django 3.2 on 2022-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FilePathField(blank=True, null=True, path='/Users/ihyeonseung/Documents/ai_cctv/media/record_img/20221126', verbose_name='섬네일'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='/Users/ihyeonseung/Documents/ai_cctv/media/record_video/20221126', verbose_name='영상'),
        ),
    ]
