# Generated by Django 3.2 on 2022-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='/Users/tae.spider_oo/Desktop/real/ai_cctv/media/record_video/20221110', verbose_name='영상'),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
