# Generated by Django 4.1.1 on 2022-10-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_image_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='count',
        ),
    ]
