# Generated by Django 4.1.1 on 2022-11-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_video_profile_delete_camera_delete_video'),
        ('camera', '0003_remove_image_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FilePathField(blank=True, null=True, path='camera/record_video', verbose_name='영상')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='상태')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('profile', models.ForeignKey(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
