# Generated by Django 3.2 on 2022-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20221110_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='/Users/tae.spider_oo/Desktop/real/ai_cctv/media/record_video/20221111', verbose_name='영상'),
        ),
    ]
