# Generated by Django 4.1.1 on 2022-11-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_video_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='record_video/', verbose_name='영상'),
        ),
    ]
