# Generated by Django 4.1.1 on 2022-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, null=True, path='/Users/tae.spider_oo/Desktop/real/ai_cctv/media', verbose_name='영상'),
        ),
    ]
