# Generated by Django 4.1.1 on 2022-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(verbose_name='날짜'),
        ),
    ]
