# Generated by Django 4.1.1 on 2022-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FileField(upload_to='test')),
            ],
        ),
    ]
